//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedFileViewer_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string Name { get; set; }
        public string Password { get; set; }
        public string CurrentDirectory { get; set; }
        public string SpyingDirectories { get; set; }
        public string Logs { get; set; }
    }
}
